### ISSUE TITLE
404 page not found within \wd\hub page

### ISSUE THREAD

**Issue by LawYard** [aandryashin/selenoid#48]
Hi!

I am trying to use selenoid with readme manual, but when Im opening hub page  `http://localhost:4444/wd/hub` there is only `404 page not found` message :(

I did all steps from your manual, but still getting error :(

```sh
curl http://localhost:4444/wd/hub -L
404 page not found
```

```sh
docker ps

CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
ba2dc8adf39b        aandryashin/selenoid:1.1.0                          "/usr/bin/selenoid -l"   12 minutes ago      Up 12 minutes       0.0.0.0:4444->4444/tcp   selenoid
```

```sh
docker logs selenoid

2017/04/13 13:04:58 Loading configuration files...
2017/04/13 13:04:58 Loaded configuration from [/etc/selenoid/browsers.json]
2017/04/13 13:04:58 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/04/13 13:04:58 Timezone: Local
2017/04/13 13:04:58 Listening on :4444
```

What I am doing wrong?(

**Comment by vania-pooh** [comment]
@LawYard just run your tests against this url:
```
http://localhost:4444/wd/hub
```
The request you are doing via ```curl``` is GET request whereas according to Selenium protocol new session is created via POST ```request```. Selenoid has no built-in UI because it can be used inside big clusters where UI is not needed. See https://github.com/aandryashin/selenoid#simple-ui on how to install a separate container with UI.

**Comment by LawYard** [comment]
I see! Thanks and sorry)
